---
title: "Tarea 1 - Resultados Experimentales"
output:
  html_document:
    df_print: paged
---

<center> <h1>Tarea 2: Frequentist Inference </h1> </center>
<center><strong>CC6104: Statistical Thinking</strong></center>
#### **Integrantes :** 

- Nicolás García Ríos

#### **Cuerpo Docente:**

- Profesor: Felipe Bravo M.
- Auxiliar: Sebastian Bustos e Ignacio Meza D.
            


```{r, eval=TRUE}
# Manipulación de estructuras
library(tidyverse)
library(dplyr)
library(tidyr)

# Para realizar plots
#library(scatterplot3d)
library(ggplot2)
# library(plotly)

# Manipulación de varios plots en una imagen.
# library(gridExtra)
# library(grid)
```


## Importacion de valores
```{r, eval=TRUE}
random.abb = read.table("Resultados/aleatorioAbb.txt")
random.avl = read.table("Resultados/aleatorioAvl.txt")
random.splay = read.table("Resultados/aleatorioSplay.txt")
random.btree16 = read.table("Resultados/aleatorioBtree16.txt")
random.btree256 = read.table("Resultados/aleatorioBtree256.txt")
random.btree4096 = read.table("Resultados/aleatorioBtree4096.txt")

```

```{r, eval=TRUE}
Experimento_aleatorio <-  data.frame(Operacion = integer(),
                                     V1 = double(),
                                     Estructura = factor()) 

z <- data.frame(Operacion = c(1:1000), V1 = random.abb, Estructura = "ABB")
Experimento_aleatorio <- rbind(Experimento_aleatorio, z)

z <- data.frame(Operacion = c(1:1000), V1 = random.avl, Estructura = "AVL")
Experimento_aleatorio <- rbind(Experimento_aleatorio, z)

z <- data.frame(Operacion = c(1:1000), V1 = random.splay, Estructura = "Splay")
Experimento_aleatorio <- rbind(Experimento_aleatorio, z)

z <- data.frame(Operacion = c(1:1000), V1 = random.btree16, Estructura = "BTree16")
Experimento_aleatorio <- rbind(Experimento_aleatorio, z)

z <- data.frame(Operacion = c(1:1000), V1 = random.btree256, Estructura = "BTree256")
Experimento_aleatorio <- rbind(Experimento_aleatorio, z)

z <- data.frame(Operacion = c(1:1000), V1 = random.btree4096, Estructura = "BTree4096")
Experimento_aleatorio <- rbind(Experimento_aleatorio, z)

```


```{r, eval=TRUE}
plot <- ggplot(data = Experimento_aleatorio, aes(x=Operacion, y=V1), inherit.aes = FALSE) + 
  geom_line(aes(colour=Estructura)) +
  xlab("Iteraciones") +  
  ylab("Tiempo") + 
  ggtitle("Tiempo por cada segmento de operaciones\nExperimento aleatorio") + 
  theme(plot.title = element_text(hjust = 0.5))
plot

```


---

&nbsp;
<hr />
<p style="text-align: center;">A work by <a href="https://github.com/Nicolas-Francisco/ABB_efficiency_study">cd</a></p>

<!-- Add icon library -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css">

<!-- Add font awesome icons -->
<p style="text-align: center;">
    <a href="https://github.com/Nicolas-Francisco/ABB_efficiency_study"><i class="fab fa-github" style='font-size:30px'></i></a>
</p>



&nbsp;